### ISSUE TITLE
在Ambari上安装MongoDB组件失败

### ISSUE THREAD

**Issue by ExcelLeft** [cas-bigdatalab/ambari-mongodb-cluster#3]
共有5台机器131-135，131可以启动，132启动报错
错误日志：
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/ambari-mongodb-cluster-no-monitor/package/scripts/mongo_db.py", line 163, in <module>
    MongoMaster().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 375, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/ambari-mongodb-cluster-no-monitor/package/scripts/mongo_db.py", line 75, in start
    ,logoutput=True)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 262, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 303, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'mongod -f /etc/mongod.conf --shardsvr  -replSet shard2 -port 27018 -dbpath /var/lib/mongo/shard2 -oplogSize 100 -logpath /var/log/mongodb/shard2.log -pidfilepath /var/run/mongodb/shard1.pid  ' returned 1. about to fork child process, waiting until server is ready for connections.
forked process: 5072
ERROR: child process failed, exited with error number 1

**Comment by excelwang** [comment]
fixed
